# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_auto_20171006_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='user_type',
            field=models.CharField(choices=[('Tourist', 'Tourist'), ('Student', 'Student'), ('Business', 'Businessman')], default='Student', max_length=20),
        ),
    ]
