# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20171023_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('TOURIST', 'Tourist'), ('BUSINESS', 'Business'), ('STUDENT', 'Student')], max_length=15),
        ),
    ]
