# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_profile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(choices=[('College', 'College'), ('Library', 'Library'), ('Industry', 'Industry'), ('Hotel', 'Hotel'), ('Park', 'Park'), ('Zoo', 'Zoo'), ('Museum', 'Museum'), ('Restaurant', 'Restaurant'), ('Mall', 'Mall')], max_length=100),
        ),
    ]
