# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_auto_20171023_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='map_link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='data',
            name='short_description',
            field=models.TextField(max_length=200),
        ),
    ]
