# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_auto_20171023_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 18, 26, 50, 589818, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 18, 26, 50, 589896, tzinfo=utc)),
        ),
    ]
