# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20171024_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='city',
            field=models.CharField(choices=[('All Cities', 'All Cities'), ('Brisbane', 'Brisbane'), ('Sydney', 'Sydney'), ('Melbourne', 'Melbourne')], default='Brisbane', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='state',
            field=models.CharField(choices=[('All States', 'All States'), ('QLD', 'QLD'), ('NSW', 'NSW'), ('VIC', 'VIC'), ('ACT', 'ACT'), ('TAS', 'TAS'), ('SA', 'SA'), ('NT', 'NT'), ('WA', 'WA')], default='QLD', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(choices=[('All Categories', 'All Categories'), ('College', 'College/Schools'), ('Library', 'Library'), ('Industry', 'Industry'), ('Hotel', 'Hotel'), ('Park', 'Park'), ('Zoo', 'Zoo'), ('Museum', 'Museum'), ('Restaurant', 'Restaurant'), ('Mall', 'Mall')], max_length=100),
        ),
    ]
