# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_auto_20171024_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
